/* eslint-disable @typescript-eslint/no-var-requires */
export const IntroOtf = require('./fonts/Intro.otf')
export const IntroWoff = require('./fonts/Intro.woff')
export const IntroRegularOtf = require('./fonts/IntroRegular.otf')
export const IntroRegularWoff = require('./fonts/IntroRegular.woff')
export const MuseoSansOtf = require('./fonts/MuseoSans.otf')
export const MuseoSansWoff = require('./fonts/MuseoSans.woff')
export const LgTtf = require('./fonts/lg.ttf')
export const LgWOff = require('./fonts/lg.woff')
export const LgWSvg = require('./fonts/lg.svg')
